### PR TITLE
login page completed

### PR DESCRIPTION
**Pull request by jitanshuraut**
image

### CODE REVIEW

**Comment by GDSCIIITSurat** [comment]
@jitanshuraut There is also supposed to be a landing page, so keep a button to click on the login page, which will open the page you have created. 
You can look at the html branch website.

**Comment by GDSCIIITSurat** [comment]
There is an error in App.js, while compiling. Please try to resolve this error

**Comment by GDSCIIITSurat** [comment]
@jitanshuraut also comment the issue you have solved

**Comment by jitanshuraut** [comment]
#3  issue solved

**Pull request merged**
