### PR TITLE
Html

### PR DESCRIPTION
**Pull request by Worriedhenry**

### CODE REVIEW

**Comment by GDSCIIITSurat** [comment]
the password should should hide character by character while typing, and i think you have removed the contact number field from signup page.

**Comment by GDSCIIITSurat** [comment]
also tag the issue you are solving

**Comment by Worriedhenry** [comment]
> the password should should hide character by character while typing, and i think you have removed the contact number field from signup page.

I have seen a lots of website were password is visible when we first create our account , but i will correct it . I have not removed the contact field . Only three fields were there that's why i asked to add more fields . So should i add contact field ??

**Comment by GDSCIIITSurat** [comment]
Yes add the contact number field, also add name field

**Pull request closed without merging**
